# Generated by Django 5.2 on 2025-05-27 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brivo', '0003_alter_usuario_turma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livro',
            options={'ordering': ['titulo']},
        ),
    ]
